# core/management/commands/clients_seed.py
"""
Seeds the client portfolio from the export Client-2026-08-13.csv.

Source
──────
  - Client-2026-08-13.csv (58 records) — companies (entreprise) and
    individuals (particulier) currently in the client base, with legal/
    fiscal identifiers (NIF, NIS, RC, article d'imposition, NIN for
    individuals) as registered with the tax/trade authorities.

Notes
─────
  - Records are matched by  (case-insensitive) to decide
    create vs. skip/update, since the CSV's own "id" column is just the
    source export's row id, not a guaranteed stable key here.
  - Two near-duplicate "EURL ALPHAS SERVICES" rows exist in the source
    CSV (differing only in address formatting / RC punctuation); both
    are seeded as-is rather than silently merged, since the source data
    doesn't clarify which is authoritative.

Run
───
    python manage.py clients_seed
    python manage.py clients_seed --force   # overwrite existing records
"""

from __future__ import annotations

import datetime

from django.core.management.base import BaseCommand

# ─────────────────────────── raw data ──────────────────────────────────────

CLIENTS = [
    {
        "client_type": "entreprise",
        "name": "Cevital Industries",
        "forme_juridique": "SPA",
        "address": "Zone Industrielle, Port de Béjaïa",
        "postal_code": "06000",
        "city": "Béjaïa",
        "phone": "034 22 50 00",
        "email": "securite@cevital.com",
        "website": "",
        "activity_sector": "Agroalimentaire",
        "contact_name": "Lynda Moussaoui",
        "contact_phone": "0661 44 55 66",
        "contact_email": "l.moussaoui@cevital.com",
        "nin": "",
        "nif": "000600333300201",
        "article_imposition": "06333300201",
        "nis": "060033330020134",
        "rc": "06/00-3333002B19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "particulier",
        "name": "Dr. Samy Belkacem",
        "forme_juridique": "",
        "address": "15 Cité des Pins, El Biar",
        "postal_code": "16030",
        "city": "Alger",
        "phone": "0550 33 44 55",
        "email": "s.belkacem@gmail.com",
        "website": "",
        "activity_sector": "Médecine du Travail",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "198506160160042",
        "nif": "",
        "article_imposition": "",
        "nis": "",
        "rc": "",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": True,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "Entreprise Nationale des Travaux aux Puits — ENTP",
        "forme_juridique": "SPA",
        "address": "BP 199, Hassi Messaoud",
        "postal_code": "30500",
        "city": "Hassi Messaoud",
        "phone": "029 73 00 01",
        "email": "securite@entp.dz",
        "website": "",
        "activity_sector": "Services Pétroliers",
        "contact_name": "Omar Zerrouki",
        "contact_phone": "0772 55 66 77",
        "contact_email": "o.zerrouki@entp.dz",
        "nin": "",
        "nif": "003000999900501",
        "article_imposition": "30999900501",
        "nis": "300099990050167",
        "rc": "30/00-9999005B19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "ETB  BAZIZI HAMIDA ( KH TRANSFO)",
        "forme_juridique": "Autre",
        "address": "Amizour  Commune Amizour",
        "postal_code": "",
        "city": "Bejaia",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "société d’installation électriques et maintenance  Industrielle",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "28506400019514000600",
        "article_imposition": "06020366633",
        "nis": "298506400019530",
        "rc": "25 A 5824628-00/06",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "EURL AFNES-PROJECT",
        "forme_juridique": "EURL",
        "address": "CITE RYM SIDI ACHOUR COOP IMMOB IHCENE BT°01",
        "postal_code": "",
        "city": "Annaba",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Installation et Maintenance Industrielle",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "000623036433719",
        "article_imposition": "23019505645",
        "nis": "000623010300376",
        "rc": "06B0364337-00/23",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "EURL  ALPHAS  SERVICES",
        "forme_juridique": "EURL",
        "address": "Cité 2038 logts, Bt 35 Bab Ezouar, Alger",
        "postal_code": "",
        "city": "",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Maintenance et Montage des  Pompes Hydrauliques",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "002216105098376",
        "article_imposition": "061014515192",
        "nis": "002216210218558",
        "rc": "22 B 1050983-00/16",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "EURL ALPHAS SERVICES",
        "forme_juridique": "EURL",
        "address": "Cité 2038 Logts, Bt 35, Bab Ezzouar, Alger",
        "postal_code": "",
        "city": "Alger",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Maintenance et Montage des Pompes Hydrauliques",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "002216105098376",
        "article_imposition": "061014515192",
        "nis": "002216210218558",
        "rc": "22B1050983-00/16",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "EURL BAIT EL OUTOUR EL ALAMIA",
        "forme_juridique": "EURL",
        "address": "Cité Kaaboub Coop Belle Vue Section 07 Groupe 911 Rdc",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Fabrication Des Produits Cosmétiques et d'hygiène Corporelle",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001619009208992",
        "article_imposition": "19018604901",
        "nis": "001619010011762",
        "rc": "16B0092089-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "EURL G S AUTOMATION",
        "forme_juridique": "EURL",
        "address": "43 Rue El Joundi Boukhaloua Cheikh, Local N°04, Es Seddikia",
        "postal_code": "",
        "city": "Oran",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Engineering & Services",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001631011645745",
        "article_imposition": "316464471038",
        "nis": "001631030034561",
        "rc": "16B0116457-00/31",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "EURL PRO TAM STEEL",
        "forme_juridique": "EURL",
        "address": "Parc industriell section 09 groupe 243 lots n 66, ouled sabor",
        "postal_code": "19000",
        "city": "setif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "transformation et fabrication des métaux ferreux et non ferreux",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "00221900950414019001",
        "article_imposition": "19470020852",
        "nis": "002219010072555",
        "rc": "22 B 0095041-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "EURL SATEREX",
        "forme_juridique": "EURL",
        "address": "Zone Industrielle, Extension Lot N°92 (Section 20 Flot 138), Sétif",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Fabrication de Produits Électroniques et Électro-Ménagers",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "000419008557395",
        "article_imposition": "19018309011",
        "nis": "000419011230367",
        "rc": "04B0085573-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "EURL SOCIETE YAAKOUB ABDELOUARETH",
        "forme_juridique": "EURL",
        "address": "Zone d'activité N°01 rdc N°3 Setif 19000",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Production des boissons non alcoolisées",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001419009138932",
        "article_imposition": "19018001059",
        "nis": "",
        "rc": "14B0091389-19/00",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "EURL SOCIETE ZOUAOUI",
        "forme_juridique": "EURL",
        "address": "Section N°23 groupement N°38 EL-Barriaka commune Guedjal",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Production panneaux sandwichs & accessoires",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "00051900863802819003",
        "article_imposition": "19170440908",
        "nis": "",
        "rc": "05B0086380-19/03",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "EURL TAHWEEL DZ",
        "forme_juridique": "EURL",
        "address": "Zone Act Art 5 Eme Tranche Ilot 18 Sec 309",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Fabrication Industrielle d'Articles De Sport et Campement",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "002219009505042",
        "article_imposition": "19018404021",
        "nis": "002219010072849",
        "rc": "22B0095050-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "GOLDEN BODY PRODUCTION",
        "forme_juridique": "Autre",
        "address": "Zone d'Activité Artisanale Classe 10 Sec 282/283/284 Oued Sabor",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Production des produits diététiques",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "002019009412767",
        "article_imposition": "19011162144",
        "nis": "",
        "rc": "20B0094127-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "Groupe Hasnaoui",
        "forme_juridique": "SARL",
        "address": "Route Nationale 7, Zone d'Activité",
        "postal_code": "22000",
        "city": "Sidi Bel Abbès",
        "phone": "048 75 10 10",
        "email": "direction@groupe-hasnaoui.dz",
        "website": "",
        "activity_sector": "BTP / Construction",
        "contact_name": "Rachid Hasnaoui",
        "contact_phone": "0771 88 99 00",
        "contact_email": "r.hasnaoui@groupe-hasnaoui.dz",
        "nin": "",
        "nif": "002200777700301",
        "article_imposition": "22777700301",
        "nis": "220077770030145",
        "rc": "22/00-7777003B19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "HALLIBURTON ENERGY SERVICES INC ALGERIA DIVISION",
        "forme_juridique": "SARL",
        "address": "Résidence Noor 10 Rue Yahia Ben Hayet, Hydra, Alger",
        "postal_code": "",
        "city": "Alger",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Service Pétrolier",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "308029000015471",
        "article_imposition": "16450140481",
        "nis": "099916451138515",
        "rc": "02/2023",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "Lafarge Algérie",
        "forme_juridique": "SPA",
        "address": "Usine de Meftah — Zone Industrielle",
        "postal_code": "28000",
        "city": "M'Sila",
        "phone": "035 55 00 10",
        "email": "hse@lafarge.dz",
        "website": "",
        "activity_sector": "Matériaux de Construction",
        "contact_name": "Nadia Benali",
        "contact_phone": "0560 11 22 33",
        "contact_email": "n.benali@lafarge.dz",
        "nin": "",
        "nif": "002800222200401",
        "article_imposition": "28222200401",
        "nis": "280022220040156",
        "rc": "28/00-2222004B19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "LAKRACHE TOUFIK",
        "forme_juridique": "Autre",
        "address": "Zone d'Activité Ouled Saber",
        "postal_code": "",
        "city": "Ouled Saber",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Production Industrielle des Éléments en Béton Non Assemblés",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "169190101459111",
        "article_imposition": "19470020730",
        "nis": "196919010145923",
        "rc": "99A0430872-19/02",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "auto_entrepreneur",
        "name": "Meziani Conseil HSE",
        "forme_juridique": "",
        "address": "Cité El Hidhab, Bloc 12, Sétif",
        "postal_code": "19000",
        "city": "Sétif",
        "phone": "0770 12 34 56",
        "email": "a.meziani.hse@gmail.com",
        "website": "",
        "activity_sector": "Conseil HSE",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001905678901234",
        "article_imposition": "19567890123",
        "nis": "",
        "rc": "",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "AE-2023-19-00587",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": True,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "startup",
        "name": "SafetyTech DZ",
        "forme_juridique": "SARL",
        "address": "Cyber Parc Sidi Abdallah, Bâtiment B",
        "postal_code": "16303",
        "city": "Alger",
        "phone": "023 12 34 56",
        "email": "contact@safetytech.dz",
        "website": "",
        "activity_sector": "Technologies HSE / SaaS",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001600888800701",
        "article_imposition": "16888800701",
        "nis": "160088880070189",
        "rc": "16/00-8888007B23",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "ANIE-2023-ST-04521",
        "label_startup_date": "2023-06-15",
        "programme_accompagnement": "NEXUS",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL A2M ELECTRONICS",
        "forme_juridique": "SARL",
        "address": "Z.I N°23 a lot n°32 bis",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Industrie électroménager",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001019008854771",
        "article_imposition": "",
        "nis": "001019010000771",
        "rc": "10B0088547-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL Alger Chimie",
        "forme_juridique": "SARL",
        "address": "Lot n°33, zone industrielle Oued Smar",
        "postal_code": "",
        "city": "Alger",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Travaux de Construction",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "099916020438623",
        "article_imposition": "16158447021",
        "nis": "099916020438623",
        "rc": "99B0007933-00/16",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL ALGERIA HAM MOTORS",
        "forme_juridique": "SARL",
        "address": "Zone d'Activité, 74 Lot N°4, Ain Azel, Sétif",
        "postal_code": "",
        "city": "Ain Azel",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Fabrication de Motocycles",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "0013L9009059593",
        "article_imposition": "19402988015",
        "nis": "",
        "rc": "1380090595-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL  ALPHAS  Algérie Pompes Hydrauliques Accessoires",
        "forme_juridique": "SARL",
        "address": "Cité 112 logts, quartie seghire Bt 04 Bp488 liberté",
        "postal_code": "",
        "city": "Bejaia",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Société de Production Pompes Hydrauliques Accessoires",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "0998 0601 82572 09",
        "article_imposition": "061014515192",
        "nis": "0996 0601 03025 44",
        "rc": "98 B 0182572-00/06",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL ALPHAS Algérie Pompes Hydrauliques Accessoires",
        "forme_juridique": "SARL",
        "address": "Cité 112 Logts, Quartier Seghir Bt 04 Bp 488, Liberté, Béjaïa",
        "postal_code": "",
        "city": "Béjaïa",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Production de Pompes Hydrauliques et Accessoires",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "099806018257209",
        "article_imposition": "061014515192",
        "nis": "099606010302544",
        "rc": "98B0182572-00/06",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL BELIEDELICE",
        "forme_juridique": "SARL",
        "address": "Zone Industrielle, Lot 225 Classe 10, Groupements 300-299-290-291, Ouled Saber, Sétif",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Production Agroalimentaire",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001619009211972",
        "article_imposition": "19470140326",
        "nis": "001619470015254",
        "rc": "16B0092119-19/00",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL CHEKHCHOUKH ET NENNI PLAST",
        "forme_juridique": "SARL",
        "address": "Cité 8 Logts Participatif Baatouche Bloc 03",
        "postal_code": "",
        "city": "Bordj Bou Arreridj",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Première Transformation de la Matière Plastique de Base",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001334046457553",
        "article_imposition": "34010509380",
        "nis": "002019260002170",
        "rc": "13B0464575-00/34",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL EIMI TRANSFO",
        "forme_juridique": "SARL",
        "address": "Ain Mousse n°764 Bâtiment F03, Sétif",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Maintenance des Transformateurs",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "002419009609655",
        "article_imposition": "19010317643",
        "nis": "002419010105563",
        "rc": "24 B 0096096-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL EL BARAKA FOOD INVESTISSEMENT",
        "forme_juridique": "SARL",
        "address": "Coop Immob Et Salam, Cité Laid Dahoui, Local N°B11 RDC, Sétif",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Production Industrielle de Crème Glacée et Autres Produits Glacés",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001419009104377",
        "article_imposition": "19018702823",
        "nis": "",
        "rc": "14B0091043/19-00",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL EL BARAKA FOOD ONE",
        "forme_juridique": "SARL",
        "address": "Coop Immob Et Salam, Cité Laid Dahoui, Local N°B11 RDC, Sétif",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Importation d'Huiles Animales et Végétales et Autres Matières Grasses",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "002119009453738",
        "article_imposition": "19338358021",
        "nis": "",
        "rc": "21B0094537/19-00",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL EL BARAKA FOOD TWO",
        "forme_juridique": "SARL",
        "address": "Coop Immob Houria Et Salam, Cité Laid Dahoui, Local N°B11 RDC, Sétif",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Importation des Matières Premières et Produits Destinés à l'Industrie Agroalimentaire",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "002119009453738",
        "article_imposition": "19338358021",
        "nis": "",
        "rc": "21B0094537/19-00",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL EL WATANIA GLASS",
        "forme_juridique": "SARL",
        "address": "Z.I SIDI KHALD SEC 13 GP 254 BOUIRA",
        "postal_code": "10000",
        "city": "BOUIRA",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "fabrication industrielle  façonnage  et transformation de verre",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001510028411838",
        "article_imposition": "",
        "nis": "0015110010008669",
        "rc": "10/00-0284118 B 15",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL GROUPE RIADH EL-FETH",
        "forme_juridique": "SARL",
        "address": "BD Beggag Bouzid Cité Financiere",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Fabrication De Cables Electriques Et Telephoniques",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "09971900820164600000",
        "article_imposition": "",
        "nis": "099719010778514",
        "rc": "97B0082016-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL IBN AOUF IMPORT & EXPORT REC",
        "forme_juridique": "SARL",
        "address": "Mechta Ouled Darouche, Ain Lahdjra, 19013 Sétif",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Importation de Cycles et Motocycles et leurs Accessoires",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "000319008518129",
        "article_imposition": "19181709021",
        "nis": "000319200545455",
        "rc": "03 B 0085181-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL INSPECTA INTERNATIONAL ALGERIA",
        "forme_juridique": "SARL",
        "address": "N°83 B, 1ère Étage BAT A, Arzew, Oran",
        "postal_code": "",
        "city": "Oran",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Asset Integrity Management & Well Services",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "002216101758634",
        "article_imposition": "31061445031",
        "nis": "002216520019258",
        "rc": "22 B1017586-31/00",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL LAMSAT KABIR",
        "forme_juridique": "SARL",
        "address": "KHALFOUNE SEC 08 GR 57",
        "postal_code": "19000",
        "city": "SETIF",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Transformation produits alimentaire",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "00241900957928719001",
        "article_imposition": "19338553041",
        "nis": "002419330047252",
        "rc": "24 B 0095792",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL LOUAI CATRING SERVICE",
        "forme_juridique": "SARL",
        "address": "Cité Bouchama Proj 04 Logts Lot 4, Détachement Touskoz Lot 06 RDC",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Entreprise de Service Hôteliers et de Restauration (Catering)",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001121014373517",
        "article_imposition": "20117304389",
        "nis": "197319010305541",
        "rc": "11B0143735-00/21",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL Metal Steel Company .LTD Setif",
        "forme_juridique": "SARL",
        "address": "Cité Houari Boumediene Rue Ounis Hamlaoui",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Fabrication métal (fonderie)",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001519009174778",
        "article_imposition": "19206116073",
        "nis": "001519200026459",
        "rc": "15B0091747-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL MEZLOUG METAL HEMAMID TAHAR ET LYAZID",
        "forme_juridique": "SARL",
        "address": "Ouled Saifi BP N°76, Mezloug",
        "postal_code": "19130",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Fabrication Métallique — Galvanisation à Chaud",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "000419008569006",
        "article_imposition": "19330198021",
        "nis": "000419330566444",
        "rc": "04B008569-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL MOF VET",
        "forme_juridique": "SARL",
        "address": "63 Lots N°12 Ain Azel 19007, Wilaya de Sétif",
        "postal_code": "",
        "city": "Ain Azel",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Fabrication de Produits pour l'Alimentation des Animaux",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "00081900871483119006",
        "article_imposition": "19402981055",
        "nis": "",
        "rc": "08B0087148-06/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL NEDJMEDINE PLAST",
        "forme_juridique": "SARL",
        "address": "RCD EL MALHA AIN ARNAT",
        "postal_code": "19100",
        "city": "sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "premiere transformation de la matiere plastuique de base",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "002119009400445",
        "article_imposition": "19269490041",
        "nis": "002019260002170",
        "rc": "20B0094004-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL NICE PLUS",
        "forme_juridique": "SARL",
        "address": "Zone Industrielle Salah Bey Setif",
        "postal_code": "19000",
        "city": "sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Fabrication Détergents",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001319009071883",
        "article_imposition": "19390513429",
        "nis": "001319390048738",
        "rc": "13 B 0090718 - 00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL RONIX",
        "forme_juridique": "SARL",
        "address": "FID SMARA SEC 06 GRP N12 N 01 BAZER SAKRA",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Fabrication d'Emballages en Toutes Matières",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001819200047451",
        "article_imposition": "19018404021",
        "nis": "001819200047451",
        "rc": "18B0093479-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL SANSIRO COSMETIC",
        "forme_juridique": "SARL",
        "address": "sahou section 09 lot de pr 47 ain oulmene",
        "postal_code": "19002",
        "city": "setif",
        "phone": "036527557",
        "email": "",
        "website": "",
        "activity_sector": "fabrication produit cosmetique et parapharmaceutique",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001719009286473",
        "article_imposition": "",
        "nis": "001719128004055",
        "rc": "19/00-009286b17",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL SETIF CITERNES",
        "forme_juridique": "SARL",
        "address": "zone d’activité 2éme tranche N°17 sétif, algerie.",
        "postal_code": "19000",
        "city": "sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Fabrication d’articles en plastique",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001719009277061",
        "article_imposition": "19018054081",
        "nis": "001719010032364",
        "rc": "17B0092770-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL SETIF MEDIC",
        "forme_juridique": "SARL",
        "address": "N°30 Rue Hamadou Torki Cité Tlidjene",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Commerce de Gros de Produits Pharmaceutiques",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "000819008771459",
        "article_imposition": "19012916024",
        "nis": "000819010054947",
        "rc": "08 B 0087714-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL SETIF MEDIC Production de Produits Pharmaceutiques",
        "forme_juridique": "SARL",
        "address": "ZI Toussa Classe N° 20 Groupe N°81 Ilot N°36",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Production de Produits Pharmaceutiques",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "0081900877145919004",
        "article_imposition": "19016311031",
        "nis": "000819010054947",
        "rc": "08 B 0087714-04/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL SILVERTON",
        "forme_juridique": "SARL",
        "address": "ZI section 26 groupe 100 lot N°73 guellal",
        "postal_code": "19000",
        "city": "sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "fabrication des produits electroniques et electromenagers",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "00041900855870819001",
        "article_imposition": "19481904001",
        "nis": "000419010469646001",
        "rc": "19/01-0085587 B 04",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL SMOFE",
        "forme_juridique": "SARL",
        "address": "CITE TELIDJENE",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Importation des Équipements et Matériels pour la Fabrication",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "000319008503407",
        "article_imposition": "19013149011",
        "nis": "000319010143268",
        "rc": "03B0085034-19/00",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SARL THAFATHE EL ACHIR",
        "forme_juridique": "SARL",
        "address": "lots 180, rue belouadah lekhloufi elachir",
        "postal_code": "34195",
        "city": "BBA",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "catering",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001734046565096",
        "article_imposition": "",
        "nis": "001734070015066",
        "rc": "17B0465650-00",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SNC KEBICHE ABDELHALIM ET CIE",
        "forme_juridique": "SNC",
        "address": "ELKEF LAHMAR",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Fabrication Métallique — galvanisation à chaud",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "000419008571081",
        "article_imposition": "19343224044",
        "nis": "000419340810946",
        "rc": "04B0085710-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SNC SAKHRA URBANISME ET CONSTRUC",
        "forme_juridique": "SNC",
        "address": "Cité Bahlouli, El-Eulma",
        "postal_code": "",
        "city": "El-Eulma",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "ETPBH",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "000719008683119",
        "article_imposition": "19206146391",
        "nis": "000719200000371",
        "rc": "07B0086831-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SOCIETE D'ETUDES TECHNIQUES DE SETIF",
        "forme_juridique": "SARL",
        "address": "Route des Abattoirs BP 89, Sétif 19000",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Études Techniques",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "099919008329067",
        "article_imposition": "19011767171",
        "nis": "097919010016831",
        "rc": "99 B 0083290-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "Sonatrach SPA",
        "forme_juridique": "SPA",
        "address": "Djenane El Malik, Hydra",
        "postal_code": "16035",
        "city": "Alger",
        "phone": "021 54 60 00",
        "email": "hse@sonatrach.dz",
        "website": "",
        "activity_sector": "Pétrole & Gaz",
        "contact_name": "Mohamed Aït Saïd",
        "contact_phone": "0551 22 33 44",
        "contact_email": "m.aitsaid@sonatrach.dz",
        "nin": "",
        "nif": "001600555500101",
        "article_imposition": "16555500101",
        "nis": "160055550010123",
        "rc": "16/00-5555001B19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SPA ACG SIM",
        "forme_juridique": "SPA",
        "address": "EL HAMOUL CLASSE 13 GP 69 ET 67 EL KARMA",
        "postal_code": "",
        "city": "Oran",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Transformation Des Produits Alimentaires",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "001609080924405",
        "article_imposition": "",
        "nis": "001609010028853",
        "rc": "16B0809244-00/31",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "SPA BIOREAL PHARM ETS ELEULMA",
        "forme_juridique": "SPA",
        "address": "Mechta Bourioune, Partie 04, Groupement de Propriétés N°39, Commune Bazar Sekra, El Eulma, Sétif",
        "postal_code": "",
        "city": "El Eulma",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Vente et Distribution de Produits Pharmaceutiques",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "099916000959666",
        "article_imposition": "19310139296",
        "nis": "099516120567227",
        "rc": "99B000959604/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
    {
        "client_type": "entreprise",
        "name": "WEG ALGERIA MOTOROS SPA",
        "forme_juridique": "SPA",
        "address": "Zone industrielle LEHLATMA01/03, commune De Guidjel",
        "postal_code": "",
        "city": "Sétif",
        "phone": "",
        "email": "",
        "website": "",
        "activity_sector": "Production de moteurs électriques pour les appareils electromagnets",
        "contact_name": "",
        "contact_phone": "",
        "contact_email": "",
        "nin": "",
        "nif": "002219009506760",
        "article_imposition": "19018690021",
        "nis": "",
        "rc": "22B0095067-00/19",
        "rib": "",
        "tin": "",
        "carte_auto_entrepreneur": "",
        "label_startup_number": "",
        "label_startup_date": "",
        "programme_accompagnement": "",
        "is_tva_exempt": False,
        "is_active": True,
        "notes": "",
    },
]

# ─────────────────────────── command ───────────────────────────────────────


class Command(BaseCommand):
    help = "Seed client portfolio from Client-2026-08-13.csv export."

    def add_arguments(self, parser):
        parser.add_argument(
            "--force",
            action="store_true",
            help="Overwrite existing records (matched by name, case-insensitive).",
        )

    def handle(self, *args, **options):
        force = options["force"]
        self._seed_clients(force)

    # ── helpers ──────────────────────────────────────────────────────────
    def _ok(self, msg: str):
        self.stdout.write(self.style.SUCCESS(f"  ✓ {msg}"))

    def _skip(self, msg: str):
        self.stdout.write(f"  – {msg} (already exists, skipped)")

    def _info(self, msg: str):
        self.stdout.write(self.style.MIGRATE_HEADING(f"\n► {msg}"))

    @staticmethod
    def _parse_date(value):
        if not value:
            return None
        return datetime.datetime.strptime(value, "%Y-%m-%d").date()

    # ── clients ──────────────────────────────────────────────────────────
    def _seed_clients(self, force: bool):
        self._info(f"Clients ({len(CLIENTS)} records)")

        try:
            from clients.models import Client
        except ImportError:
            self.stderr.write(
                self.style.WARNING(
                    "  ⚠ Could not import Client – skipping. "
                    "Check that the 'clients' app label/model path is correct."
                )
            )
            return

        created, updated, skipped = 0, 0, 0

        for data in CLIENTS:
            data = dict(data)
            data["label_startup_date"] = self._parse_date(data.get("label_startup_date"))

            existing = Client.objects.filter(name__iexact=data["name"]).first()

            if existing:
                if force:
                    for field, value in data.items():
                        setattr(existing, field, value)
                    existing.save()
                    updated += 1
                else:
                    skipped += 1
                continue

            Client.objects.create(**data)
            created += 1

        self._ok(f"{created} created, {updated} updated, {skipped} skipped")