# formations/management/commands/formations_seed.py
"""
Seeds the institute's commercial training catalogue — every Formation
currently offered, grouped under the 9 commercial Categories.

Updated in this revision
─────────────────────────
  - Mapped ISO, Audit, Non-Conformités, Contrôle Qualité, MSA, IATF,
    and ISO 22000 to the new QMS (Management de la Qualité) category.
  - Mapped Commercial (Vente) to COM (Communication).
  - Linked existing HSE and Informatique formations to the newly added
    2025 changelog specialties.

Run
───
    python manage.py formations_seed
    python manage.py formations_seed --force
"""

from __future__ import annotations

from decimal import Decimal

from django.core.management.base import BaseCommand

FORMATIONS = [
    # ══ MANAGEMENT DES RESSOURCES HUMAINES (RH) ════════════════════════════
    (
        "RH-001",
        "Enjeux de la Fonction RH et le Management des Ressources Humaines",
        "RH",
        3,
        21,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        None,
    ),
    (
        "RH-002",
        "Gestion des Emplois et des Compétences (GPEC)",
        "RH",
        3,
        21,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        None,
    ),
    (
        "RH-003",
        "Techniques de Résolution des Conflits",
        "RH",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "RH-004",
        "Emprise du Droit de Travail National sur les Pratiques GRH",
        "RH",
        3,
        21,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        None,
    ),
    (
        "RH-005",
        "Législation et Sécurité Sociale",
        "RH",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "RH-006",
        "Analyse et Évolution des Systèmes de Rémunération",
        "RH",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "RH-007",
        "Système d'Information RH et Tableau de Bord",
        "RH",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "RH-008",
        "Les Indicateurs de Performance KPI",
        "RH",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "RH-009",
        "Politique de Rémunération",
        "RH",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "RH-010",
        "Formation ISO 9001, ISO 14001, ISO 45001",
        "QMS",
        3,
        21,
        5,
        20,
        Decimal("63000.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        3,
        "ISO",
        None,
    ),
    (
        "RH-011",
        "Élaboration des Budgets pour RH",
        "RH",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "RH-012",
        "Formation Audit SMQ",
        "QMS",
        3,
        21,
        5,
        20,
        Decimal("68000.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        None,
    ),
    (
        "RH-013",
        "Formation Gestion des Risques",
        "QMS",
        3,
        21,
        5,
        20,
        Decimal("63000.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        None,
    ),
    # ── NEW from invoices ───────────────────────────────────────────────
    (
        "TAG0714",
        "Gestion de Trésorerie",
        "GES",
        4,
        28,
        5,
        20,
        Decimal("55000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        4,
        "",
        "TAG0714",
    ),
    (
        "TAG0717",
        "Gestion du Personnel",
        "RH",
        3,
        21,
        5,
        20,
        Decimal("40000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "TAG0717",
    ),
    (
        "TAG0714",
        "Élaboration, Suivi et Analyse des Tableaux de Bord",
        "GES",
        2,
        14,
        5,
        20,
        Decimal("65000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        "TAG0714",
    ),
    (
        "TAG0714",
        "Traitement et Gestion des Non-Conformités",
        "QMS",
        3,
        21,
        5,
        20,
        Decimal("65000.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "TAG0714",
    ),
    (
        "CMS0707",
        "Contrôle de Qualité",
        "QMS",
        3,
        21,
        5,
        20,
        Decimal("50000.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "CMS0707",
    ),
    (
        "TAG1205",
        "Techniques d'Achats",
        "GES",
        3,
        21,
        5,
        20,
        Decimal("50000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "TAG1205",
    ),
    (
        "TAG1801",
        "Gestion des Stocks",
        "GES",
        3,
        21,
        5,
        20,
        Decimal("55000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "TAG1801",
    ),
    (
        "CMS0707",
        "Measurement System Analysis (MSA)",
        "QMS",
        3,
        21,
        5,
        20,
        Decimal("46000.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "CMS0707",
    ),
    (
        "CMS0707",
        "IATF 16949:2016 — Système de Management de la Qualité Automobile",
        "QMS",
        4,
        28,
        5,
        20,
        Decimal("48500.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        4,
        "",
        "CMS0707",
    ),
    (
        "IAA0713",
        "ISO 22000 — Système de Management de la Sécurité des Denrées Alimentaires",
        "QMS",
        4,
        28,
        5,
        20,
        Decimal("70000.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        4,
        "",
        "IAA0713",
    ),
    # ══ COMMUNICATION, LEADERSHIP & SOFT SKILLS (COM) ══════════════════════
    (
        "COM-001",
        "Gestion de Conflits",
        "COM",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "COM-002",
        "Maîtrise du Temps et Gestion des Priorités",
        "COM",
        4,
        28,
        5,
        20,
        Decimal("80000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        4,
        "",
        None,
    ),
    (
        "COM-003",
        "Communication Interpersonnelle et ses Techniques",
        "COM",
        3,
        21,
        5,
        20,
        Decimal("65000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        None,
    ),
    (
        "COM-004",
        "Gestion d'Équipe",
        "COM",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "COM-005",
        "Agent Commercial",
        "COM",
        3,
        21,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        None,
    ),
    (
        "COM-006",
        "Les Écrits Professionnels et Administratifs",
        "COM",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "COM-007",
        "Animation de Réunions et Prise de Parole en Public",
        "COM",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "TAG0717",
        "Leadership Managérial",
        "COM",
        2,
        14,
        5,
        20,
        Decimal("80000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        "TAG0717",
    ),
    (
        "TAG0712",
        "Commercial (Vente et Négociation)",
        "COM",
        5,
        35,
        5,
        20,
        Decimal("85000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        5,
        "",
        "TAG0712",
    ),
    # ══ MAINTENANCE & PRODUCTIQUE INDUSTRIELLE (PMD) ═══════════════════════
    (
        "PMD-001",
        "Gestion de la Maintenance Assistée par Ordinateur (GMAO) – Initiation et Viabilité",
        "PMD",
        3,
        21,
        5,
        20,
        Decimal("0"),
        "both",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        None,
    ),
    (
        "PMD-002",
        "Maintenance Basée sur la Fiabilité (RCM)",
        "PMD",
        3,
        21,
        5,
        20,
        Decimal("0"),
        "both",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        None,
    ),
    (
        "PMD-003",
        "Extraire les Bonnes Informations des Tableaux de Bord et Analyse",
        "PMD",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "PMD-004",
        "Maîtrise de la Totale Productive Maintenance (TPM)",
        "PMD",
        3,
        21,
        5,
        20,
        Decimal("0"),
        "both",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        None,
    ),
    (
        "PMD-005",
        "Formation Méthodes de Maintenance",
        "PMD",
        3,
        21,
        5,
        20,
        Decimal("0"),
        "both",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        None,
    ),
    (
        "CMS0709",
        "Fondamentaux des Opérations dans une Entreprise Industrielle (Maintenance-Production et Planification)",
        "PMD",
        3,
        21,
        5,
        20,
        Decimal("65000.00"),
        "both",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "CMS0709",
    ),
    (
        "CMS0709",
        "Maintenance Industrielle",
        "PMD",
        3,
        21,
        5,
        20,
        Decimal("60000.00"),
        "both",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "CMS0709",
    ),
    # ══ HYGIÈNE, SÉCURITÉ & ENVIRONNEMENT (HSE) ════════════════════════════
    (
        "HSE-001",
        "IOSH Managing Safely",
        "HSE",
        4,
        28,
        1,
        20,
        Decimal("65000.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        4,
        "IOSH",
        "INP1204",
    ),
    (
        "HSE-002",
        "Superviseur HSE",
        "HSE",
        3,
        21,
        1,
        20,
        Decimal("50000.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "INP1204",
    ),
    (
        "HSE-003",
        "Protections Électriques (Réseaux & Centrales)",
        "HSE",
        3,
        21,
        5,
        20,
        Decimal("0"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "ELE0702",
    ),
    (
        "HSE-004",
        "Leadership et Culture HSE",
        "HSE",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "HSE-005",
        "La Veille Réglementaire HSE (Lois, Règles, Normes)",
        "HSE",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "HSE-006",
        "Sécurité Basée sur le Comportement (BBS)",
        "HSE",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "HSE-007",
        "Les Techniques d'Investigation des Accidents et Incidents",
        "HSE",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "both",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "HSE-008",
        "Commission Paritaire d'Hygiène et de Sécurité (CPHS)",
        "HSE",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "HSE-009",
        "Habilitation à la Conduite des Chariots Élévateurs",
        "HSE",
        2,
        14,
        1,
        20,
        Decimal("22000.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        "MME1202",
    ),
    (
        "HSE-010",
        "Hazard Analysis Critical Control Point (HACCP)",
        "HSE",
        3,
        21,
        5,
        20,
        Decimal("0"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "IAA0713",
    ),
    (
        "HSE-011",
        "Habilitation Électrique",
        "HSE",
        3,
        21,
        5,
        20,
        Decimal("0"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "ELE0702",
    ),
    (
        "HSE-012",
        "Habilitation à l'Utilisation des Produits Chimiques",
        "HSE",
        4,
        28,
        5,
        20,
        Decimal("50000.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        4,
        "",
        "CIP0703",
    ),
    (
        "HSE-013",
        "Premier Secours",
        "HSE",
        1,
        7,
        5,
        20,
        Decimal("0"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        1,
        "",
        None,
    ),
    (
        "HSE-014",
        "Lutte Contre l'Incendie",
        "HSE",
        1,
        7,
        5,
        20,
        Decimal("0"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        1,
        "",
        None,
    ),
    (
        "HSE-015",
        "Habilitation Travail en Hauteur",
        "HSE",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        None,
    ),
    (
        "HSE-016",
        "La Conduite en Sécurité des Engins",
        "HSE",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        "MME1802",
    ),
    (
        "HSE-017",
        "Risque Hydrogène Sulfuré H2S",
        "HSE",
        1,
        7,
        5,
        20,
        Decimal("0"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        1,
        "",
        None,
    ),
    (
        "HSE-018",
        "Atmosphère Explosive – Niveau 01 (ISM-ATEX 1)",
        "HSE",
        3,
        21,
        1,
        10,
        Decimal("0"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        3,
        "ISM",
        "INP1204",
    ),
    (
        "HSE-019",
        "Atmosphère Explosive – Niveau 02 E (ISM-ATEX 2EM)",
        "HSE",
        5,
        35,
        1,
        10,
        Decimal("180000.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        5,
        "ISM",
        "INP1204",
    ),
    (
        "HSE-020",
        "La Conduite Sécuritaire des Ponts Roulants",
        "HSE",
        2,
        14,
        5,
        20,
        Decimal("0"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        "MME1204",
    ),
    (
        "HSE-021",
        "Délégué Environnement",
        "HSE",
        3,
        21,
        5,
        20,
        Decimal("0"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "MEE2512",
    ),
    (
        "HSE-022",
        "Formation Sensibilisation aux Risques liés à l'Activité de Carrières",
        "HSE",
        2,
        14,
        5,
        30,
        Decimal("45000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        2,
        "",
        "MIC1901",
    ),
    # ── NEW from invoices ───────────────────────────────────────────────
    (
        "INP1204",
        "Formation des Agents de Sécurité",
        "HSE",
        3,
        21,
        5,
        20,
        Decimal("55000.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "INP1204",
    ),
    (
        "INP1204",
        "Sûreté Interne",
        "HSE",
        3,
        21,
        5,
        20,
        Decimal("50000.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "INP1204",
    ),
    (
        "MME1802",
        "Conduite en Sécurité du Transport de Personnel",
        "HSE",
        1,
        7,
        5,
        20,
        Decimal("32000.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        1,
        "",
        "MME1802",
    ),
    (
        "HRT1803",
        "Bonnes Pratiques d'Hygiène et de Restauration",
        "HSE",
        4,
        28,
        5,
        20,
        Decimal("70000.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        4,
        "",
        "HRT1803",
    ),
    # ══ INFORMATIQUE, BUREAUTIQUE & DATA ANALYSE (INF) ═════════════════════
    (
        "INF-001",
        "Excel & Word Avancés",
        "INF",
        3,
        21,
        5,
        20,
        Decimal("0"),
        "both",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        None,
    ),
    (
        "INF-002",
        "Power BI",
        "INF",
        3,
        21,
        5,
        20,
        Decimal("0"),
        "both",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "INT2505",
    ),
    # ══ BÂTIMENT & TRAVAUX PUBLICS (BAT) ═══════════════════════════════════
    (
        "BTP0724",
        "Architecture",
        "BAT",
        7,
        49,
        5,
        20,
        Decimal("10000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        7,
        "",
        "BTP0724",
    ),
    (
        "BTP0716",
        "Suivi de Chantier",
        "BAT",
        3,
        21,
        5,
        20,
        Decimal("20000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "BTP0716",
    ),
    (
        "BTP0720",
        "Conducteur de Travaux",
        "BAT",
        5,
        35,
        5,
        20,
        Decimal("20000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        5,
        "",
        "BTP0720",
    ),
    # ══ GESTION ADMINISTRATIVE, FINANCIÈRE & LOGISTIQUE (GES) ══════════════
    (
        "TAG0714",
        "Comptabilité Générale",
        "GES",
        5,
        35,
        5,
        20,
        Decimal("30000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        5,
        "",
        "TAG0714",
    ),
    # ══ INDUSTRIE PHARMACEUTIQUE & SANTÉ (PHA) ═════════════════════════════
    (
        "IAA0713",
        "Lutte contre les Nuisibles dans les Entrepôts et Centres de Distribution Pharmaceutique",
        "PHA",
        3,
        21,
        5,
        20,
        Decimal("100595.57"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        3,
        "",
        "IAA0713",
    ),
    (
        "TAG1801",
        "Gestion des Approvisionnements en Distribution Pharmaceutique (Achat Local & Import/Export)",
        "PHA",
        5,
        35,
        5,
        20,
        Decimal("75800.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        5,
        "",
        "TAG1801",
    ),
    (
        "TAG0710",
        "Organisation et Gestion des Affaires Réglementaires (Autorisations, Déclarations, Vigilance)",
        "PHA",
        4,
        28,
        5,
        20,
        Decimal("57500.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        4,
        "",
        "TAG0710",
    ),
    (
        "CMS0707",
        "Initiation au Change Control et à la Gestion des Déviations en Milieu Distributeur",
        "PHA",
        4,
        28,
        5,
        20,
        Decimal("50230.50"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        4,
        "",
        "CMS0707",
    ),
    (
        "TAG0712",
        "Étude de Marché et Sélection des Produits",
        "PHA",
        1,
        7,
        5,
        20,
        Decimal("50000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        1,
        "",
        "TAG0712",
    ),
    (
        "TAG0711",
        "Étude Technico-Économique et Élaboration de Business Plan pour le Lancement de Nouveaux Produits",
        "PHA",
        1,
        7,
        5,
        20,
        Decimal("37191.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        1,
        "",
        "TAG0711",
    ),
    (
        "TAG1205",
        "Qualification et Agrément des Fournisseurs et Sous-Traitants Logistiques",
        "PHA",
        1,
        7,
        5,
        20,
        Decimal("87500.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        1,
        "",
        "TAG1205",
    ),
    (
        "IAA0713",
        "Bonnes Pratiques de Fabrication (BPF) Avancée",
        "PHA",
        1,
        7,
        5,
        20,
        Decimal("72500.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        1,
        "",
        "IAA0713",
    ),
    (
        "IAA0713",
        "Initiation à l'Audit BPF et Rédaction des Rapports",
        "PHA",
        1,
        7,
        5,
        20,
        Decimal("42500.00"),
        "both",
        True,
        Decimal("10"),
        Decimal("20"),
        1,
        "",
        "IAA0713",
    ),
    (
        "TAG0717",
        "Modalités de Recrutement et Induction en Industrie Pharmaceutique",
        "PHA",
        1,
        7,
        5,
        20,
        Decimal("60172.47"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        1,
        "",
        "TAG0717",
    ),
    (
        "TAG0717",
        "Gestion des Formations et Qualification du Personnel",
        "PHA",
        1,
        7,
        5,
        20,
        Decimal("32000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        1,
        "",
        "TAG0717",
    ),
    (
        "TAG1801",
        "Gestion des Flux en Industrie Pharmaceutique",
        "PHA",
        1,
        7,
        5,
        20,
        Decimal("30000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        1,
        "",
        "TAG1801",
    ),
    (
        "TAG0710",
        "Maîtrise et Gestion Documentaire",
        "PHA",
        1,
        7,
        5,
        20,
        Decimal("65000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        1,
        "",
        "TAG0710",
    ),
    (
        "TAG0710",
        "Pratique d'Exécution du Processus de Gestion Documentaire",
        "PHA",
        1,
        7,
        5,
        20,
        Decimal("45000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        1,
        "",
        "TAG0710",
    ),
    (
        "TAG0710",
        "Site Master File (SMF)",
        "PHA",
        1,
        7,
        5,
        20,
        Decimal("35000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        1,
        "",
        "TAG0710",
    ),
    (
        "TAG0710",
        "Manuel Qualité",
        "PHA",
        1,
        7,
        5,
        20,
        Decimal("38000.00"),
        "theory_only",
        False,
        Decimal("10"),
        Decimal("20"),
        1,
        "",
        "TAG0710",
    ),
]


class Command(BaseCommand):
    help = "Seed the commercial training catalogue (all Formations)."

    def add_arguments(self, parser):
        parser.add_argument("--force", action="store_true")

    def handle(self, *args, **options):
        force = options["force"]

        try:
            from formations.models import Formation, Category, Specialty
        except ImportError as exc:
            self.stderr.write(self.style.ERROR(f"  Import error: {exc}"))
            return

        self.stdout.write(self.style.MIGRATE_HEADING("\n► Formations"))

        CATEGORY_NAMES = {
            "RH": "Management des Ressources Humaines",
            "COM": "Communication, Leadership & Soft Skills",
            "QMS": "Management de la Qualité & Conformité",
            "PMD": "Maintenance & Productique Industrielle",
            "HSE": "Hygiène, Sécurité & Environnement",
            "INF": "Informatique, Bureautique & Data Analyse",
            "BAT": "Bâtiment & Travaux Publics",
            "GES": "Gestion Administrative, Financière & Logistique",
            "PHA": "Industrie Pharmaceutique & Santé",
        }
        cat_cache = {}
        for key, name in CATEGORY_NAMES.items():
            try:
                cat_cache[key] = Category.objects.get(name=name)
            except Category.DoesNotExist:
                self.stderr.write(
                    self.style.ERROR(
                        f"  ✗ Category '{name}' not found — "
                        f"run `python manage.py categories_seed` first."
                    )
                )

        specialty_cache = {}
        for sp in Specialty.objects.select_related("branch").all():
            specialty_cache[sp.reference_root] = sp

        created_count = updated_count = skipped_count = 0

        for row in FORMATIONS:
            (
                code,
                title,
                cat_key,
                duration_days,
                duration_hours,
                min_p,
                max_p,
                base_price,
                eval_type,
                produces_cert,
                passing_score,
                max_score,
                min_attendance_days,
                accreditation_body,
                specialty_ref,
            ) = row

            category = cat_cache.get(cat_key)
            specialty_obj = None
            if specialty_ref:
                specialty_obj = specialty_cache.get(specialty_ref)
                if specialty_obj is None:
                    self.stderr.write(
                        self.style.WARNING(
                            f"  ⚠ Specialty '{specialty_ref}' not found — "
                            f"run `python manage.py specialities_seed` first. "
                            f"Formation '{title}' will have no specialty link."
                        )
                    )

            defaults = {
                "title": title,
                "title_ar": "",
                "category": category,
                "code": code,
                "duration_days": duration_days,
                "duration_hours": duration_hours,
                "min_participants": min_p,
                "max_participants": max_p,
                "evaluation_type": eval_type,
                "produces_certificate": produces_cert,
                "passing_score": passing_score,
                "max_score": max_score,
                "min_attendance_days": min_attendance_days,
                "accreditation_body": accreditation_body,
                "is_active": True,
                "specialty": specialty_obj,
            }

            obj, was_created = Formation.objects.get_or_create(
                title=title,
                defaults=defaults,
            )

            if was_created:
                created_count += 1
                self.stdout.write(
                    self.style.SUCCESS(
                        f"  ✓ [{obj.code}] {title}"
                        + (f"  ⟶ {specialty_ref}" if specialty_ref else "")
                    )
                )
            elif force:
                for field, value in defaults.items():
                    setattr(obj, field, value)
                obj.save()
                updated_count += 1
                self.stdout.write(
                    self.style.SUCCESS(
                        f"  ✓ [{obj.code}] {title} — updated"
                        + (f"  ⟶ {specialty_ref}" if specialty_ref else "")
                    )
                )
            else:
                skipped_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"\n  Formations — {created_count} created, "
                f"{updated_count} updated, {skipped_count} skipped "
                f"(total {len(FORMATIONS)})."
            )
        )
