# Generated by Django 6.0.3 on 2026-03-16 13:28

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('candidate_list', 'Liste des informations candidats'), ('attendance_sheet', 'Feuille de présence'), ('mission_order', 'Ordre de mission'), ('nominal_list', 'Liste nominale'), ('evaluation_list', "Liste des notes d'évaluation"), ('deliberation_report', 'محضر مداولات نهاية التكوين'), ('evaluation_sheet', "Fiche d'évaluation individuelle"), ('attestation', 'شهادة تكوين تأهيلي')], max_length=50)),
                ('file', models.FileField(upload_to=documents.models.session_document_path)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('day_number', models.IntegerField(blank=True, help_text='Pour les feuilles de présence (jour 1, 2, etc.)', null=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(blank=True, help_text='Null pour les documents au niveau session', null=True, on_delete=django.db.models.deletion.CASCADE, to='formations.participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.session')),
            ],
            options={
                'verbose_name': 'Document généré',
                'verbose_name_plural': 'Documents générés',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['session', 'doc_type', 'is_latest'], name='documents_g_session_e6d72c_idx'), models.Index(fields=['participant', 'doc_type', 'is_latest'], name='documents_g_partici_fc301a_idx')],
            },
        ),
    ]
