# Generated by Django 6.0.3 on 2026-03-16 13:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='Couleur')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Titre (AR)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duration_days', models.IntegerField(verbose_name='Durée (jours)')),
                ('duration_hours', models.IntegerField(verbose_name='Durée (heures)')),
                ('min_participants', models.IntegerField(verbose_name='Minimum participants')),
                ('max_participants', models.IntegerField(verbose_name='Maximum participants')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de base (DA)')),
                ('evaluation_type', models.CharField(choices=[('theory_only', 'Théorique seulement'), ('practice_only', 'Pratique seulement'), ('both', 'Théorique et pratique')], max_length=20, verbose_name="Type d'évaluation")),
                ('passing_score', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=4, verbose_name='Note de passage')),
                ('produces_certificate', models.BooleanField(default=True, verbose_name='Produit une attestation')),
                ('accreditation_body', models.CharField(blank=True, max_length=100, verbose_name="Organisme d'agrément")),
                ('legal_references', models.TextField(blank=True, verbose_name='Références légales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formations.category')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('first_name_ar', models.CharField(blank=True, max_length=50, verbose_name='Prénom (AR)')),
                ('last_name_ar', models.CharField(blank=True, max_length=50, verbose_name='Nom (AR)')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('place_of_birth', models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance')),
                ('place_of_birth_ar', models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance (AR)')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
                ('employer', models.CharField(blank=True, max_length=200, verbose_name='Employeur')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('attended', models.BooleanField(default=True, verbose_name='Présent')),
                ('attendance_per_day', models.JSONField(blank=True, default=dict, verbose_name='Présence par jour')),
                ('score_theory', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Note théorique')),
                ('score_practice', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Note pratique')),
                ('certificate_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de certificat')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='Certificat émis')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('date_start', models.DateField(verbose_name='Date début')),
                ('date_end', models.DateField(verbose_name='Date fin')),
                ('location_type', models.CharField(choices=[('institute', 'Institut'), ('on_site', 'Sur site')], max_length=20, verbose_name='Type de lieu')),
                ('external_location', models.CharField(blank=True, max_length=200, verbose_name='Lieu externe')),
                ('capacity', models.IntegerField(verbose_name='Capacité')),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('archived', 'Archivée'), ('cancelled', 'Annulée')], default='planned', max_length=20, verbose_name='Statut')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name="Raison d'annulation")),
                ('committee_members', models.JSONField(blank=True, default=list, verbose_name='Membres du comité')),
                ('specialty_code', models.CharField(blank=True, max_length=20, verbose_name='Code spécialité')),
                ('session_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro de session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-date_start'],
            },
        ),
    ]
