# Generated by Django 4.2.16 on 2026-03-23 13:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name="Note maximale de l'examen"),
        ),
        migrations.AddField(
            model_name='formation',
            name='min_attendance_days',
            field=models.IntegerField(default=1, help_text="Nombre minimum de jours de présence requis pour obtenir l'attestation", verbose_name='Présence minimale (jours)'),
        ),
        migrations.AddField(
            model_name='participant',
            name='exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Note de l'examen final — détermine la réussite et l'attribution de l'attestation", max_digits=5, null=True, verbose_name="Note d'examen final"),
        ),
        migrations.AddField(
            model_name='participant',
            name='source_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='formations.participant', verbose_name='Participant source'),
        ),
        migrations.AddField(
            model_name='session',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='Session principale (jour 1). Les sessions suivantes sont auto-générées.', verbose_name='Session principale'),
        ),
        migrations.AddField(
            model_name='session',
            name='parent_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_sessions', to='formations.session', verbose_name='Session parente'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='passing_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Note de passage'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='score_practice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note pratique (journée)'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='score_theory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note théorique (journée)'),
        ),
    ]
