# Generated by Django 6.0.3 on 2026-03-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=200, verbose_name="Nom de l'institut (FR)")),
                ('name_ar', models.CharField(max_length=200, verbose_name="Nom de l'institut (AR)")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institute/')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nif', models.CharField(max_length=20, verbose_name='NIF')),
                ('nis', models.CharField(max_length=20, verbose_name='NIS')),
                ('rc', models.CharField(max_length=20, verbose_name='RC')),
                ('article_imposition', models.CharField(max_length=20, verbose_name="Article d'imposition")),
                ('rib', models.CharField(max_length=50, verbose_name='RIB')),
                ('accreditation_number', models.CharField(max_length=50, verbose_name="Numéro d'agrément")),
                ('accreditation_date', models.DateField(verbose_name="Date d'agrément")),
                ('if_number', models.CharField(max_length=20, verbose_name='Numéro IF')),
                ('footer_fr', models.TextField(blank=True, verbose_name='Pied de page (FR)')),
                ('footer_ar', models.TextField(blank=True, verbose_name='Pied de page (AR)')),
            ],
            options={
                'verbose_name': "Informations de l'institut",
                'verbose_name_plural': "Informations de l'institut",
            },
        ),
    ]
