# Generated by Django 6.1 on 2026-08-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pv', 'Procès-verbal (PV) de délibération'), ('certificate', 'Attestation / Certificat')], max_length=20, verbose_name='Type')),
                ('period_key', models.CharField(help_text="Clé de la période sur laquelle le compteur est remis à zéro (ex. '2026-08' pour un compteur mensuel, '2026' pour un compteur annuel).", max_length=20, verbose_name='Période')),
                ('last_value', models.PositiveIntegerField(default=0, verbose_name='Dernière valeur')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compteur de séquence',
                'verbose_name_plural': 'Compteurs de séquence',
                'constraints': [models.UniqueConstraint(fields=('kind', 'period_key'), name='unique_sequence_kind_period')],
            },
        ),
    ]
