# Generated by Django 6.1 on 2026-08-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sequencecounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencecounter',
            name='kind',
            field=models.CharField(choices=[('pv', 'Procès-verbal (PV) de délibération'), ('certificate', 'Attestation / Certificat'), ('mission_order', 'Ordre de mission')], max_length=20, verbose_name='Type'),
        ),
    ]
