# Generated by Django 6.1 on 2026-08-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instituteinfo_pv_notification_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVDefaultSignatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم و اللقب')),
                ('role', models.CharField(max_length=150, verbose_name='الصفة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, help_text='Décochez pour retirer ce membre des propositions par défaut sans le supprimer.', verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Membre par défaut du PV',
                'verbose_name_plural': 'Membres par défaut du PV',
                'ordering': ['order', 'id'],
            },
        ),
    ]
