# Generated by Django 6.1 on 2026-08-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instituteinfo_pv_notification_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم و اللقب')),
                ('role', models.CharField(help_text='مثال : مدير المؤسسة، مدير الدراسات و العلاقات العامة', max_length=150, verbose_name='الصفة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, help_text='الأعضاء غير النشطين لا يظهرون تلقائياً في محاضر المداولات الجديدة.', verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'عضو افتراضي في اللجنة',
                'verbose_name_plural': 'الأعضاء الافتراضيون في اللجنة (محضر المداولات)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
