# Generated by Django 6.0.3 on 2026-03-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la salle')),
                ('capacity', models.IntegerField(verbose_name='Capacité')),
                ('equipment', models.TextField(blank=True, verbose_name='Équipements')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('first_name_ar', models.CharField(blank=True, max_length=50, verbose_name='Prénom (AR)')),
                ('last_name_ar', models.CharField(blank=True, max_length=50, verbose_name='Nom (AR)')),
                ('specialty', models.CharField(max_length=200, verbose_name='Spécialité')),
                ('professional_address', models.TextField(blank=True, verbose_name='Adresse professionnelle')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('employment_type', models.CharField(choices=[('internal', 'Interne'), ('external', 'Externe')], default='external', max_length=20, verbose_name="Type d'emploi")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qualifications', models.ManyToManyField(blank=True, related_name='qualified_trainers', to='formations.formation', verbose_name='Formations qualifiées')),
            ],
            options={
                'verbose_name': 'Formateur',
                'verbose_name_plural': 'Formateurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
