from django.urls import path
from . import views, views_print

app_name = "documents"

urlpatterns = [
    # ── Dashboard / history ─────────────────────────────────────────────
    path(
        "sessions/<int:session_pk>/documents/",
        views.document_dashboard,
        name="dashboard",
    ),
    path(
        "sessions/<int:session_pk>/documents/history/",
        views.document_history,
        name="history",
    ),
    # ── Generate (now redirect to print views) ──────────────────────────
    path(
        "sessions/<int:session_pk>/generate/candidate-list/",
        views.generate_candidate_list_view,
        name="generate_candidate_list",
    ),
    path(
        "sessions/<int:session_pk>/generate/attendance-sheet/",
        views.generate_attendance_sheet_view,
        name="generate_attendance_sheet",
    ),
    path(
        "sessions/<int:session_pk>/generate/mission-order/",
        views.generate_mission_order_view,
        name="generate_mission_order",
    ),
    path(
        "sessions/<int:session_pk>/generate/nominal-list/",
        views.generate_nominal_list_view,
        name="generate_nominal_list",
    ),
    path(
        "sessions/<int:session_pk>/generate/evaluation-list/",
        views.generate_evaluation_list_view,
        name="generate_evaluation_list",
    ),
    path(
        "sessions/<int:session_pk>/generate/deliberation-report/",
        views.generate_deliberation_report_view,
        name="generate_deliberation_report",
    ),
    path(
        "sessions/<int:session_pk>/committee/",
        views.set_committee_view,
        name="set_committee",
    ),
    path(
        "participants/<int:participant_pk>/generate/evaluation-sheet/",
        views.generate_evaluation_sheet_view,
        name="generate_evaluation_sheet",
    ),
    path(
        "participants/<int:participant_pk>/generate/attestation/",
        views.generate_attestation_view,
        name="generate_attestation",
    ),
    path(
        "sessions/<int:session_pk>/generate/batch-attestations/",
        views.generate_batch_attestations_view,
        name="generate_batch_attestations",
    ),
    path("documents/<int:pk>/download/", views.download_document, name="download"),
    # ── Print views (HTML, CTRL+P friendly) ────────────────────────────
    path(
        "sessions/<int:session_pk>/print/candidate-list/",
        views_print.print_candidate_list,
        name="print_candidate_list",
    ),
    path(
        "sessions/<int:session_pk>/print/attendance-sheet/",
        views_print.print_attendance_sheet,
        name="print_attendance_sheet",
    ),
    path(
        "sessions/<int:session_pk>/print/nominal-list/",
        views_print.print_nominal_list,
        name="print_nominal_list",
    ),
    path(
        "sessions/<int:session_pk>/print/evaluation-list/",
        views_print.print_evaluation_list,
        name="print_evaluation_list",
    ),
    path(
        "sessions/<int:session_pk>/print/mission-order/",
        views_print.print_mission_order,
        name="print_mission_order",
    ),
    path(
        "sessions/<int:session_pk>/print/deliberation-report/",
        views_print.print_deliberation_report,
        name="print_deliberation_report",
    ),
    path(
        "sessions/<int:session_pk>/print/batch-attestations/",
        views_print.print_batch_attestations,
        name="print_batch_attestations",
    ),
    path(
        "participants/<int:participant_pk>/print/attestation/",
        views_print.print_attestation,
        name="print_attestation",
    ),
]
