# Generated by Django 4.2.30 on 2026-08-12 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('candidate_list', 'Liste des informations candidats'), ('attendance_sheet', 'Feuille de présence'), ('mission_order', 'Ordre de mission'), ('evaluation_list', "Liste des notes d'évaluation"), ('nominal_list', 'Liste nominale'), ('deliberation_report', 'محضر مداولات نهاية التكوين'), ('evaluation_sheet', "Fiche d'évaluation individuelle"), ('attestation', 'شهادة تكوين تأهيلي')], max_length=50)),
                ('file', models.FileField(upload_to=documents.models.session_document_path)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('day_number', models.IntegerField(blank=True, help_text='Pour les feuilles de présence (jour 1, 2, etc.)', null=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document généré',
                'verbose_name_plural': 'Documents générés',
                'ordering': ['-generated_at'],
            },
        ),
    ]
