# Generated by Django 6.0.7 on 2026-08-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='doc_type',
            field=models.CharField(choices=[('candidate_list', 'Liste des informations candidats'), ('attendance_sheet', 'Feuille de présence'), ('mission_order', 'Ordre de mission'), ('evaluation_list', "Liste des notes d'évaluation"), ('nominal_list', 'Liste nominale'), ('deliberation_report', 'محضر مداولات نهاية التكوين'), ('evaluation_sheet', "Fiche d'évaluation individuelle"), ('attestation', 'شهادة تكوين تأهيلي')], max_length=50),
        ),
    ]
