# Generated by Django 4.2.30 on 2026-08-12 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='participant',
            field=models.ForeignKey(blank=True, help_text='Null pour les documents au niveau session', null=True, on_delete=django.db.models.deletion.CASCADE, to='formations.participant'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.session'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['session', 'doc_type', 'is_latest'], name='documents_g_session_e6d72c_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['participant', 'doc_type', 'is_latest'], name='documents_g_partici_fc301a_idx'),
        ),
    ]
