# Generated by Django 6.1 on 2026-08-13 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        ('formations', '0003_session_pv_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_1', models.CharField(blank=True, choices=[('A', 'A — Satisfait'), ('B', 'B — Bon'), ('C', 'C — Moyen'), ('D', 'D — Non satisfait')], max_length=1, verbose_name='1. Contenu de la formation')),
                ('grade_2', models.CharField(blank=True, choices=[('A', 'A — Satisfait'), ('B', 'B — Bon'), ('C', 'C — Moyen'), ('D', 'D — Non satisfait')], max_length=1, verbose_name='2. Durée de la formation')),
                ('grade_3', models.CharField(blank=True, choices=[('A', 'A — Satisfait'), ('B', 'B — Bon'), ('C', 'C — Moyen'), ('D', 'D — Non satisfait')], max_length=1, verbose_name='3. Supports pédagogiques')),
                ('grade_4', models.CharField(blank=True, choices=[('A', 'A — Satisfait'), ('B', 'B — Bon'), ('C', 'C — Moyen'), ('D', 'D — Non satisfait')], max_length=1, verbose_name='4. Animation du formateur')),
                ('grade_5', models.CharField(blank=True, choices=[('A', 'A — Satisfait'), ('B', 'B — Bon'), ('C', 'C — Moyen'), ('D', 'D — Non satisfait')], max_length=1, verbose_name='5. Ambiance générale')),
                ('grade_6', models.CharField(blank=True, choices=[('A', 'A — Satisfait'), ('B', 'B — Bon'), ('C', 'C — Moyen'), ('D', 'D — Non satisfait')], max_length=1, verbose_name='6. Nouvelles connaissances acquises')),
                ('grade_7', models.CharField(blank=True, choices=[('A', 'A — Satisfait'), ('B', 'B — Bon'), ('C', 'C — Moyen'), ('D', 'D — Non satisfait')], max_length=1, verbose_name='7. Réponse aux attentes/besoins')),
                ('grade_8', models.CharField(blank=True, choices=[('A', 'A — Satisfait'), ('B', 'B — Bon'), ('C', 'C — Moyen'), ('D', 'D — Non satisfait')], max_length=1, verbose_name='8. Applicabilité sur le poste de travail')),
                ('overall_satisfaction', models.CharField(blank=True, choices=[('very_satisfied', 'Très satisfait'), ('satisfied', 'Satisfait'), ('average', 'Moyen'), ('dissatisfied', 'Insatisfait')], help_text='بشكل عام، كيف تقيم هذا التدريب ؟', max_length=20, verbose_name='Appréciation générale')),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires')),
                ('filled_at', models.DateTimeField(auto_now=True, verbose_name='Dernière saisie')),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hot_evaluation', to='formations.participant', verbose_name='Participant')),
            ],
            options={
                'verbose_name': "Fiche d'évaluation à chaud",
                'verbose_name_plural': "Fiches d'évaluation à chaud",
            },
        ),
    ]
