# Generated by Django 6.1 on 2026-08-17 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_hotevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMissionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name="N° d'archivage")),
                ('employee_name', models.CharField(max_length=150, verbose_name='Nom et prénom')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='Fonction occupée')),
                ('professional_address', models.CharField(blank=True, max_length=255, verbose_name='Adresse professionnelle')),
                ('destination', models.CharField(max_length=200, verbose_name='Destination')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif de la mission')),
                ('date_start', models.DateField(verbose_name='Date de départ')),
                ('time_start', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('date_end', models.DateField(verbose_name='Date de retour')),
                ('transport_means', models.CharField(choices=[('vehicule_service', 'Véhicule de service'), ('vehicule_personnel', 'Véhicule personnel'), ('transport_commun', 'Transport en commun'), ('autre', 'Autre')], default='vehicule_service', max_length=30, verbose_name='Moyen de transport')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordre de mission (employé)',
                'verbose_name_plural': 'Ordres de mission (employés)',
                'ordering': ['-created_at'],
            },
        ),
    ]
