# Generated by Django 4.2.30 on 2026-08-12 22:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10, unique=True, verbose_name='Abréviation')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('name_ar', models.CharField(blank=True, max_length=150, verbose_name='Nom (AR)')),
                ('curriculum_type', models.CharField(choices=[('diplomante', 'Diplômante'), ('qualifiante', 'Qualifiante')], max_length=20, verbose_name='Type de cursus')),
                ('curriculum_min_months', models.IntegerField(verbose_name='Durée minimale (mois)')),
                ('curriculum_max_months', models.IntegerField(verbose_name='Durée maximale (mois)')),
            ],
            options={
                'verbose_name': 'Branche',
                'verbose_name_plural': 'Branches',
                'ordering': ['abbreviation'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='Couleur')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Titre (AR)')),
                ('code', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Code')),
                ('attestation_type', models.CharField(blank=True, choices=[('diplome', 'Diplôme'), ('certificat', 'Certificat')], max_length=20, verbose_name="Type d'attestation")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duration_days', models.IntegerField(verbose_name='Durée (jours)')),
                ('duration_hours', models.IntegerField(verbose_name='Durée (heures)')),
                ('min_participants', models.IntegerField(verbose_name='Minimum participants')),
                ('max_participants', models.IntegerField(verbose_name='Maximum participants')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de base (DA)')),
                ('evaluation_type', models.CharField(choices=[('theory_only', 'Théorique seulement'), ('practice_only', 'Pratique seulement'), ('both', 'Théorique et pratique')], max_length=20, verbose_name="Type d'évaluation")),
                ('passing_score', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Note de passage')),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name="Note maximale de l'examen")),
                ('min_attendance_days', models.IntegerField(default=1, help_text="Nombre minimum de jours de présence requis pour obtenir l'attestation", verbose_name='Présence minimale (jours)')),
                ('produces_certificate', models.BooleanField(default=True, verbose_name='Produit une attestation')),
                ('accreditation_body', models.CharField(blank=True, max_length=100, verbose_name="Organisme d'agrément")),
                ('legal_references', models.TextField(blank=True, verbose_name='Références légales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Nom complet en français/latin OPTIONNEL — au moins un nom complet (français OU arabe) est requis au total.', max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, help_text='Nom complet en français/latin OPTIONNEL — au moins un nom complet (français OU arabe) est requis au total.', max_length=50, verbose_name='Nom')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme')], help_text='Utilisé pour le décompte « منهم بنات » du محضر مداولات', max_length=1, verbose_name='Genre')),
                ('first_name_ar', models.CharField(blank=True, max_length=50, verbose_name='Prénom (AR)')),
                ('last_name_ar', models.CharField(blank=True, max_length=50, verbose_name='Nom (AR)')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('place_of_birth', models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance')),
                ('place_of_birth_ar', models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance (AR)')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
                ('employer', models.CharField(blank=True, max_length=200, verbose_name='Employeur')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('attended', models.BooleanField(default=True, verbose_name='Présent')),
                ('attendance_per_day', models.JSONField(blank=True, default=dict, verbose_name='Présence par jour')),
                ('score_theory', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note théorique (journée)')),
                ('score_practice', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note pratique (journée)')),
                ('exam_score', models.DecimalField(blank=True, decimal_places=2, help_text="Note de l'examen final — détermine la réussite et l'attribution de l'attestation", max_digits=5, null=True, verbose_name="Note d'examen final")),
                ('certificate_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de certificat')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='Certificat émis')),
                ('qr_payload', models.CharField(blank=True, help_text="Texte ou URL personnalisé encodé dans le QR code de l'attestation. Laisser vide pour utiliser le lien de vérification généré automatiquement.", max_length=500, verbose_name='Contenu du QR code (optionnel)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='Titre (AR)')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='formations.branch', verbose_name='Branche')),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'ordering': ['branch__abbreviation', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('date_start', models.DateField(verbose_name='Date début')),
                ('date_end', models.DateField(verbose_name='Date fin')),
                ('location_type', models.CharField(choices=[('institute', 'Institut'), ('on_site', 'Sur site')], max_length=20, verbose_name='Type de lieu')),
                ('external_location', models.CharField(blank=True, max_length=200, verbose_name='Lieu externe')),
                ('capacity', models.IntegerField(verbose_name='Capacité')),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('archived', 'Archivée'), ('cancelled', 'Annulée')], default='planned', max_length=20, verbose_name='Statut')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name="Raison d'annulation")),
                ('committee_members', models.JSONField(blank=True, default=list, verbose_name='Membres du comité')),
                ('specialty_code', models.CharField(blank=True, max_length=20, verbose_name='Code spécialité')),
                ('session_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro de session')),
                ('is_primary', models.BooleanField(default=True, help_text='Session principale (jour 1). Les sessions suivantes sont auto-générées.', verbose_name='Session principale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-date_start'],
            },
        ),
    ]
