# Generated by Django 4.2.30 on 2026-08-12 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('formations', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='equipment',
            field=models.ManyToManyField(blank=True, help_text='Utilisé pour détecter les doubles réservations entre sessions qui se chevauchent.', related_name='session_set', to='resources.equipment', verbose_name='Équipements réservés'),
        ),
        migrations.AddField(
            model_name='session',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation'),
        ),
        migrations.AddField(
            model_name='session',
            name='parent_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_sessions', to='formations.session', verbose_name='Session parente'),
        ),
        migrations.AddField(
            model_name='session',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.room'),
        ),
        migrations.AddField(
            model_name='session',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.trainer'),
        ),
        migrations.AddField(
            model_name='participant',
            name='employer_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
        migrations.AddField(
            model_name='participant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.session'),
        ),
        migrations.AddField(
            model_name='participant',
            name='source_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='formations.participant', verbose_name='Participant source'),
        ),
        migrations.AddField(
            model_name='formation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formations.category'),
        ),
        migrations.AddField(
            model_name='formation',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='formations.specialty', verbose_name='Spécialité'),
        ),
        migrations.AlterUniqueTogether(
            name='specialty',
            unique_together={('branch', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('session', 'last_name', 'first_name')},
        ),
    ]
