# Generated by Django 6.1 on 2026-08-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='pv_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro PV'),
        ),
    ]
