# Generated by Django 6.0.7 on 2026-08-04 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_formation_max_score_formation_min_attendance_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10, unique=True, verbose_name='Abréviation')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('name_ar', models.CharField(blank=True, max_length=150, verbose_name='Nom (AR)')),
                ('curriculum_type', models.CharField(choices=[('diplomante', 'Diplômante'), ('qualifiante', 'Qualifiante')], max_length=20, verbose_name='Type de cursus')),
                ('curriculum_min_months', models.IntegerField(verbose_name='Durée minimale (mois)')),
                ('curriculum_max_months', models.IntegerField(verbose_name='Durée maximale (mois)')),
            ],
            options={
                'verbose_name': 'Branche',
                'verbose_name_plural': 'Branches',
                'ordering': ['abbreviation'],
            },
        ),
        migrations.AddField(
            model_name='formation',
            name='attestation_type',
            field=models.CharField(blank=True, choices=[('diplome', 'Diplôme'), ('certificat', 'Certificat')], max_length=20, verbose_name="Type d'attestation"),
        ),
        migrations.AlterField(
            model_name='formation',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Code'),
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='Titre (AR)')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='formations.branch', verbose_name='Branche')),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'ordering': ['branch__abbreviation', 'code'],
                'unique_together': {('branch', 'code')},
            },
        ),
        migrations.AddField(
            model_name='formation',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='formations.specialty', verbose_name='Spécialité'),
        ),
    ]
