# Generated by Django 6.1 on 2026-08-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_session_pv_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='price_mode',
            field=models.CharField(choices=[('by_day', 'Par jour (prix de base × nombre de jours)'), ('by_person', 'Par participant (prix de base × participants)'), ('by_day_person', 'Par jour et par participant (prix de base × jours × participants)')], default='by_person', max_length=20, verbose_name='Mode de tarification'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='max_participants',
            field=models.IntegerField(default=12, verbose_name='Maximum participants'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='min_participants',
            field=models.IntegerField(default=6, verbose_name='Minimum participants'),
        ),
    ]
