# Generated by Django 6.1 on 2026-08-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0004_formation_price_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='price_mode',
        ),
        migrations.AddField(
            model_name='session',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix de ce cycle de session — peut varier d'un cycle à l'autre selon la demande.", max_digits=10, null=True, verbose_name='Prix de base (DA)'),
        ),
        migrations.AddField(
            model_name='session',
            name='invoice_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Référence/séquence de facture associée à ce cycle de session.', max_length=50, verbose_name='Numéro de facture'),
        ),
        migrations.AddField(
            model_name='session',
            name='price_mode',
            field=models.CharField(choices=[('by_day', 'Par jour (prix de base × nombre de jours)'), ('by_person', 'Par participant (prix de base × participants)'), ('by_day_person', 'Par jour et par participant (prix de base × jours × participants)')], default='by_person', max_length=20, verbose_name='Mode de tarification'),
        ),
    ]
