# Generated by Django 6.0.7 on 2026-08-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0004_branch_formation_attestation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='qr_payload',
            field=models.CharField(blank=True, help_text="Texte ou URL personnalisé encodé dans le QR code de l'attestation. Laisser vide pour utiliser le lien de vérification généré automatiquement.", max_length=500, verbose_name='Contenu du QR code (optionnel)'),
        ),
    ]
