# Generated by Django 6.1 on 2026-08-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0005_remove_formation_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro de session'),
        ),
    ]
