# Generated by Django 6.1 on 2026-08-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0005_participant_qr_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme')], help_text='Utilisé pour le décompte « منهم بنات » du محضر مداولات', max_length=1, verbose_name='Genre'),
        ),
    ]
