# Generated by Django 6.1 on 2026-08-13 03:29

import django.core.validators
import django.db.models.deletion
import formations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0006_alter_session_session_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='trainer_cost_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant direct formateur (DA)'),
        ),
        migrations.AddField(
            model_name='session',
            name='trainer_cost_mode',
            field=models.CharField(choices=[('percentage', 'Pourcentage du prix total'), ('direct', 'Montant direct')], default='percentage', max_length=20, verbose_name='Mode de rémunération du formateur'),
        ),
        migrations.AddField(
            model_name='session',
            name='trainer_cost_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Part (%) du prix total de ce cycle revenant au formateur.', max_digits=5, null=True, verbose_name='Pourcentage formateur (%)'),
        ),
        migrations.CreateModel(
            name='TrainerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant réglé (DA)')),
                ('payment_mode', models.CharField(choices=[('espece', 'Espèce'), ('cheque', 'Chèque'), ('virement_bancaire', 'Virement bancaire'), ('ccp', 'Virement CCP')], max_length=20, verbose_name='Mode de règlement')),
                ('reference', models.CharField(help_text='Auto-générée (ESP-{formateur}-{date}-{heure}) pour un règlement en espèce.', max_length=100, verbose_name='Référence de transaction')),
                ('proof_document', models.FileField(blank=True, help_text='Image ou PDF, optionnel.', null=True, upload_to=formations.models.trainer_payment_proof_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])], verbose_name='Justificatif (scan)')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Réglé le')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Confirmé par')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_payment_record', to='formations.session', verbose_name='Cycle de session')),
            ],
            options={
                'verbose_name': 'Paiement formateur',
                'verbose_name_plural': 'Paiements formateurs',
                'ordering': ['-paid_at'],
            },
        ),
    ]
