# Generated by Django 6.1 on 2026-08-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0006_participant_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(blank=True, help_text='Nom complet en français/latin OPTIONNEL — au moins un nom complet (français OU arabe) est requis au total.', max_length=50, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(blank=True, help_text='Nom complet en français/latin OPTIONNEL — au moins un nom complet (français OU arabe) est requis au total.', max_length=50, verbose_name='Nom'),
        ),
    ]
