# Generated by Django 6.1 on 2026-08-13 04:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0007_session_trainer_cost_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpayment',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note interne'),
        ),
        migrations.AddField(
            model_name='trainerpayment',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmé'), ('pending', 'En attente'), ('cancelled', 'Annulé')], default='confirmed', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='trainerpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='trainerpayment',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Réglé le'),
        ),
        migrations.AlterField(
            model_name='trainerpayment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_payments_set', to='formations.session', verbose_name='Cycle de session'),
        ),
    ]
