# Generated by Django 6.1 on 2026-08-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0007_alter_participant_first_name_and_more'),
        ('resources', '0002_local_remove_room_equipment_room_equipment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='equipment',
            field=models.ManyToManyField(blank=True, help_text='Utilisé pour détecter les doubles réservations entre sessions qui se chevauchent.', related_name='session_set', to='resources.equipment', verbose_name='Équipements réservés'),
        ),
    ]
