# Generated by Django 6.1 on 2026-08-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0008_trainerpayment_notes_trainerpayment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='mission_order_number',
            field=models.CharField(blank=True, max_length=20, verbose_name="Numéro d'ordre de mission"),
        ),
    ]
