# Generated by Django 6.1 on 2026-08-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0009_session_mission_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='pv_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='Numéro PV'),
        ),
    ]
