# Generated by Django on 2026-08-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0010_alter_session_pv_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre (AR)'),
        ),
    ]
