# Generated by Django 4.2.30 on 2026-08-12 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('local_type', models.CharField(choices=[('atelier', 'Atelier'), ('entrepot', 'Entrepôt'), ('garage', 'Garage'), ('bureau', 'Bureau'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type')),
                ('address', models.TextField(blank=True, verbose_name='Adresse (si distincte du siège)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locaux',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la salle')),
                ('capacity', models.IntegerField(verbose_name='Capacité')),
                ('equipment_notes', models.TextField(blank=True, verbose_name='Équipements fixes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('first_name_ar', models.CharField(blank=True, max_length=50, verbose_name='Prénom (AR)')),
                ('last_name_ar', models.CharField(blank=True, max_length=50, verbose_name='Nom (AR)')),
                ('specialty', models.CharField(max_length=200, verbose_name='Spécialité')),
                ('professional_address', models.TextField(blank=True, verbose_name='Adresse professionnelle')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('employment_type', models.CharField(choices=[('internal', 'Interne'), ('external', 'Externe')], default='external', max_length=20, verbose_name="Type d'emploi")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qualifications', models.ManyToManyField(blank=True, related_name='qualified_trainers', to='formations.formation', verbose_name='Formations qualifiées')),
            ],
            options={
                'verbose_name': 'Formateur',
                'verbose_name_plural': 'Formateurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('category', models.CharField(choices=[('machine', 'Machine'), ('tool', 'Outil'), ('safety_gear', 'Équipement de sécurité'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie')),
                ('inventory_code', models.CharField(blank=True, max_length=50, verbose_name="Référence d'inventaire")),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('under_maintenance', 'En maintenance'), ('out_of_service', 'Hors service')], default='available', max_length=20, verbose_name='État')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name="Date d'acquisition")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_set', to='resources.local', verbose_name='Local assigné')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_set', to='resources.room', verbose_name='Salle assignée')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['name'],
            },
        ),
    ]
