# Generated by Django 6.0.7 on 2026-08-04 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('local_type', models.CharField(choices=[('atelier', 'Atelier'), ('entrepot', 'Entrepôt'), ('garage', 'Garage'), ('bureau', 'Bureau'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type')),
                ('address', models.TextField(blank=True, verbose_name='Adresse (si distincte du siège)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locaux',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='room',
            old_name='equipment',
            new_name='equipment_notes',
        ),
        migrations.AlterField(
            model_name='room',
            name='equipment_notes',
            field=models.TextField(blank=True, verbose_name='Équipements fixes'),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('category', models.CharField(choices=[('machine', 'Machine'), ('tool', 'Outil'), ('safety_gear', 'Équipement de sécurité'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie')),
                ('inventory_code', models.CharField(blank=True, max_length=50, verbose_name="Référence d'inventaire")),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('under_maintenance', 'En maintenance'), ('out_of_service', 'Hors service')], default='available', max_length=20, verbose_name='État')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name="Date d'acquisition")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_set', to='resources.room', verbose_name='Salle assignée')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_set', to='resources.local', verbose_name='Local assigné')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['name'],
            },
        ),
    ]
