# Generated by Django 6.1 on 2026-08-12 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='equipment_notes',
            field=models.TextField(blank=True, verbose_name='Équipements fixes (notes libres)'),
        ),
        migrations.CreateModel(
            name='EquipmentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateTimeField(auto_now_add=True, verbose_name='Alloué le')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Libéré le')),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alloué par')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='resources.equipment', verbose_name='Équipement')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Libéré par')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_allocations', to='resources.room', verbose_name='Salle')),
                ('session', models.ForeignKey(blank=True, help_text='Vide = affectation permanente à la salle (hors session).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_allocations', to='formations.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': "Allocation d'équipement",
                'verbose_name_plural': "Historique d'allocation des équipements",
                'ordering': ['-allocated_at'],
            },
        ),
    ]
