# Generated by Django 6.1 on 2026-08-12 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_initial'),
        ('resources', '0002_equipment_allocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': "Catégorie d'actif pédagogique",
                'verbose_name_plural': "Catégories d'actifs pédagogiques",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PedagogicalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Référence')),
                ('unit', models.CharField(choices=[('piece', 'Pièce'), ('pack', 'Lot / Pack'), ('box', 'Boîte'), ('ream', 'Rame'), ('liter', 'Litre'), ('kg', 'Kilogramme'), ('other', 'Autre')], default='piece', max_length=20, verbose_name='Unité')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('minimum_stock', models.PositiveIntegerField(default=0, help_text="En dessous de ce seuil, l'actif est signalé comme stock bas.", verbose_name="Seuil d'alerte")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='resources.assetcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Actif pédagogique',
                'verbose_name_plural': 'Actifs pédagogiques',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('restock', 'Réapprovisionnement'), ('delivery', 'Livraison / Consommation')], max_length=20, verbose_name='Type')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Effectué le')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('session', models.ForeignKey(blank=True, help_text='Renseigné uniquement pour une livraison consommée dans une session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_movements', to='formations.session', verbose_name='Session')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='resources.pedagogicalasset', verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Historique des mouvements de stock',
                'ordering': ['-performed_at'],
            },
        ),
    ]
