# Generated by Django 6.1 on 2026-08-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_assetcategory_pedagogicalasset_assetmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmovement',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix total du mouvement'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire (au moment du mouvement)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix total (pour la quantité)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire'),
        ),
        migrations.AddField(
            model_name='equipmentallocation',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité réservée'),
        ),
        migrations.AddField(
            model_name='equipmentallocation',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Retours partiels (ex : surplus rendu avant la fin de session).', verbose_name='Quantité retournée'),
        ),
        migrations.AddField(
            model_name='equipmentallocation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix total réservé'),
        ),
        migrations.AddField(
            model_name='equipmentallocation',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Prix unitaire (au moment de l'allocation)"),
        ),
        migrations.AddField(
            model_name='pedagogicalasset',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valeur totale du stock'),
        ),
        migrations.AddField(
            model_name='pedagogicalasset',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='movement_type',
            field=models.CharField(choices=[('restock', 'Réapprovisionnement'), ('delivery', 'Livraison / Consommation'), ('return', 'Retour (surplus / autre)')], max_length=20, verbose_name='Type'),
        ),
    ]
