# Generated by Django 6.1 on 2026-08-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_trainer_cv_trainer_contact_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='default_cost_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant fixe par défaut, utilisé si le mode direct est retenu.', max_digits=10, null=True, verbose_name='Montant direct par défaut (DA)'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='default_cost_mode',
            field=models.CharField(choices=[('percentage', 'Pourcentage du prix total'), ('direct', 'Montant direct')], default='percentage', max_length=20, verbose_name='Mode de rémunération par défaut'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='default_cost_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Part par défaut (%) du prix total de la formation revenant au formateur.', max_digits=5, null=True, verbose_name='Pourcentage par défaut (%)'),
        ),
    ]
